export type QuestionSeed = [
  prompt: string,
  correctAnswer: string,
  distractor1: string,
  distractor2: string,
  distractor3: string
];

export const quizQuestionSets: Record<number, QuestionSeed[]> = {
  1: [
    ["Il complesso Khast Imam si sviluppò vicino alla tomba di quale studioso?", "Abu Bakr Kaffal ash-Shashi", "Al-Khwarizmi", "Avicenna", "Al-Biruni"],
    ["Quale celebre manoscritto è custodito nella biblioteca di Khast Imam?", "Il Corano di Uthman", "Il Codice di Hammurabi", "Il Libro dei Re di Firdusi", "Il Canone di Avicenna"],
    ["Su quale materiale sono scritte le 353 pagine del Corano di Uthman conservato a Tashkent?", "Pergamena", "Carta di gelso", "Papiro", "Seta"],
    ["La madrasa Barak Khan fu costruita principalmente in quale secolo?", "XVI secolo", "X secolo", "XIII secolo", "XIX secolo"],
    ["Quale legame aveva il fondatore della madrasa Barak Khan con Ulugh Beg?", "Era suo nipote", "Era suo padre", "Era il suo astronomo", "Era il suo architetto"],
    ["Che cosa significa il nome Chorsu?", "Incrocio di quattro strade", "Mercato della seta", "Grande cupola blu", "Porta della città"],
    ["In quale parte di Tashkent si trova il bazar Chorsu?", "Eski Shahar, la città vecchia", "Nel quartiere diplomatico", "Accanto all'aeroporto", "Nella città sovietica"],
    ["Quale elemento architettonico rende subito riconoscibile il padiglione alimentare di Chorsu?", "Una grande cupola blu", "Una torre dell'orologio", "Quattro minareti", "Un tetto di legno piatto"],
    ["Quale di questi è un prodotto caseario tipico venduto a Chorsu?", "Suzma", "Nori", "Feta greca", "Mozzarella di bufala"],
    ["In quale anno iniziò la costruzione della metropolitana di Tashkent?", "1973", "1947", "1984", "2001"],
    ["Quante stazioni aveva la prima linea della metro di Tashkent all'apertura?", "9", "5", "14", "22"],
    ["Perché le stazioni della metro di Tashkent sono spesso paragonate a gallerie d'arte?", "Per mosaici, motivi decorativi e ritratti", "Perché ospitano quadri in vendita", "Per le pareti interamente di vetro", "Perché sono tutte musei archeologici"],
    ["Quale fu la prima linea della metropolitana di Tashkent?", "Chilanzar", "Yunusabad", "Uzbekistan", "Sergeli"],
    ["In quale anno fu inaugurata la linea Uzbekistan della metro?", "1984", "1977", "1991", "2001"],
    ["In quale anno la piazza centrale assunse il nome di Piazza dell'Indipendenza?", "1991", "1966", "1977", "2000"]
  ],
  2: [
    ["Che cosa indica il nome Ichan Kala?", "La città interna fortificata", "Il mercato coperto", "Il palazzo estivo", "La necropoli reale"],
    ["Quale riconoscimento internazionale possiede Ichan Kala?", "Patrimonio mondiale UNESCO", "Capitale europea della cultura", "Riserva della biosfera", "Sito naturale Ramsar"],
    ["Circa quanto sono alte le mura di Ichan Kala?", "10 metri", "3 metri", "25 metri", "40 metri"],
    ["Quanti edifici monumentali conta approssimativamente Ichan Kala secondo l'UNESCO?", "51", "12", "110", "250"],
    ["Qual era la funzione di Khiva per le carovane dirette verso la Persia?", "Ultima grande sosta prima del deserto", "Porto sul Mar Caspio", "Stazione ferroviaria", "Miniera di rame"],
    ["Perché il minareto Kalta Minor rimase incompiuto?", "Il khan morì durante i lavori", "Mancò l'acqua per l'impasto", "Un terremoto distrusse la base", "Fu vietato dai mercanti"],
    ["Quale altezza avrebbe dovuto raggiungere Kalta Minor secondo il progetto?", "Circa 80 metri", "Circa 25 metri", "Circa 45 metri", "Circa 120 metri"],
    ["In quale anno iniziò la costruzione di Kalta Minor?", "1852", "1688", "1127", "1920"],
    ["Che cosa distingue il rivestimento di Kalta Minor?", "È interamente coperto da piastrelle smaltate e maiolica", "È scolpito in marmo bianco", "È rivestito di rame", "È dipinto solo all'interno"],
    ["Che cos'era Kunya Ark?", "La cittadella e residenza dei khan", "Un caravanserraglio", "Una scuola coranica", "Il quartiere dei ceramisti"],
    ["In quale anno fu completata Kunya Ark?", "1688", "1598", "1855", "1911"],
    ["Quale attività avveniva nella piazza davanti a Kunya Ark?", "Parate e addestramento militare", "Corse di cammelli", "Tintura della seta", "Aste di manoscritti"],
    ["Quante colonne lignee sostengono la sala della Moschea Juma secondo l'UNESCO?", "212", "40", "98", "365"],
    ["Quale soluzione illumina la Moschea Juma di Khiva?", "Due lucernari ottagonali", "Una vetrata occidentale", "Un cortile senza tetto", "Candele in quattro minareti"],
    ["In quale anno Khiva divenne capitale del khanato?", "1598", "1220", "1688", "1871"]
  ],
  3: [
    ["Che cosa significa Kyzylkum?", "Sabbia rossa", "Mare asciutto", "Terra dei khan", "Pianura verde"],
    ["Tra quali due grandi fiumi si estende il Kyzylkum?", "Amu Darya e Syr Darya", "Volga e Don", "Indo e Gange", "Tigri ed Eufrate"],
    ["Quale mare si trova a nord-ovest del Kyzylkum?", "Mar d'Aral", "Mar Caspio", "Mar Nero", "Lago Balkhash"],
    ["Quale catena montuosa delimita il deserto verso nord-est?", "Tien Shan", "Himalaya", "Caucaso", "Zagros"],
    ["Quale pianta è particolarmente adatta alle sabbie del Kyzylkum?", "Saxaul", "Bambù", "Baobab", "Mangrovia"],
    ["Quale animale raro è protetto nella riserva del Kyzylkum?", "Cervo di Bukhara", "Panda gigante", "Lince iberica", "Orso polare"],
    ["Quale paesaggio prevale nel Kyzylkum?", "Sabbioso e roccioso", "Foresta pluviale", "Tundra", "Palude tropicale"],
    ["Quale antica rotta commerciale attraversava l'area tra Khiva e Bukhara?", "La Via della Seta", "La Via dell'Ambra", "La Via Appia", "La rotta delle spezie marittima"],
    ["Da oltre quanto tempo Bukhara è abitata secondo l'UNESCO?", "Più di 2.000 anni", "Circa 500 anni", "Circa 800 anni", "Più di 5.000 anni documentati"],
    ["In quale anno il centro storico di Bukhara entrò nella lista UNESCO?", "1993", "1977", "2000", "2016"],
    ["Per quale caratteristica urbana Bukhara è particolarmente importante?", "È un esempio molto completo di città medievale centroasiatica", "È una capitale romana intatta", "È una città scavata nella roccia", "È il più antico porto dell'Asia"],
    ["Quale monumento di Bukhara risale al X secolo?", "Mausoleo dei Samanidi", "Palazzo Khudoyar Khan", "Kalta Minor", "Museo dei Timuridi"],
    ["Nel 1220 Bukhara subì l'invasione di quale esercito?", "Mongolo", "Ottomano", "Romano", "Britannico"],
    ["Quale sovrano conquistò Bukhara nel 1370?", "Amir Temur", "Alessandro Magno", "Babur", "Pietro il Grande"],
    ["Tra IX e XVI secolo, quante madrase erano presenti a Bukhara secondo le fonti storiche UNESCO?", "Più di 100", "Meno di 10", "Esattamente 25", "Circa 40"]
  ],
  4: [
    ["Quale materiale domina l'esterno del Mausoleo dei Samanidi?", "Mattone cotto", "Marmo bianco", "Legno di noce", "Piastrelle blu"],
    ["A chi viene attribuita la costruzione del Mausoleo dei Samanidi?", "Ismail Samani", "Ulugh Beg", "Khudoyar Khan", "Muhammad Amin Khan"],
    ["Quale forma geometrica descrive meglio il Mausoleo dei Samanidi?", "Un cubo sormontato da una cupola", "Un ottagono con minareto", "Una piramide", "Una basilica a tre navate"],
    ["Perché le quattro facciate del Mausoleo dei Samanidi appaiono equivalenti?", "Per la sua composizione centrica", "Perché furono ricostruite insieme", "Per orientarlo verso quattro bazar", "Per nascondere l'ingresso"],
    ["Qual era la principale funzione dell'Ark di Bukhara?", "Cittadella e sede dei governanti", "Osservatorio astronomico", "Mercato della seta", "Monastero"],
    ["Quale studioso è tradizionalmente associato alla biblioteca dell'Ark?", "Avicenna", "Galileo", "Marco Polo", "Confucio"],
    ["Che cosa significa la parola hauz in Bolo Hauz?", "Vasca o stagno", "Cupola", "Fortezza", "Scuola"],
    ["Quali monumenti formano il nucleo del Poi Kalon?", "Minareto, moschea e madrasa", "Palazzo, terme e teatro", "Bazar, fortezza e osservatorio", "Mausoleo, ponte e caravanserraglio"],
    ["Chi fece costruire il minareto Kalon nel 1127?", "Arslankhan", "Amir Temur", "Ulugh Beg", "Said Alim Khan"],
    ["Oltre alla chiamata alla preghiera, quale funzione ebbe il minareto Kalon?", "Torre di osservazione e segnale per le carovane", "Mulino a vento", "Deposito d'acqua", "Laboratorio di ceramica"],
    ["A quali secoli appartiene nel complesso l'ensemble Poi Kalon?", "Dal XII al XVI secolo", "Dal VI all'VIII secolo", "Dal XVIII al XX secolo", "Solo al XV secolo"],
    ["Che cosa significa il nome Chor Minor?", "Quattro torri", "Mercato nuovo", "Palazzo della luna", "Porta occidentale"],
    ["Chi fece costruire Chor Minor nel 1807?", "Khalifa Niyazkul", "Ismail Samani", "Yalangtush Bahadur", "Suyunchkhoja Khan"],
    ["Quale funzione aveva il piano superiore di Chor Minor?", "Biblioteca", "Prigione", "Zecca", "Sala del trono"],
    ["Che cosa indica la parola tim nei mercati coperti di Bukhara?", "Uno spazio commerciale chiuso", "Una moneta d'argento", "Una torre di guardia", "Un canale sotterraneo"]
  ],
  5: [
    ["Che cosa significa approssimativamente Sitorai Mokhi Khosa?", "Palazzo simile alle stelle e alla luna", "Casa delle quattro torri", "Fortezza della sabbia rossa", "Giardino del re vivente"],
    ["Per quale sovrano fu realizzata la parte nuova di Sitorai Mokhi Khosa?", "Said Alim Khan", "Ulugh Beg", "Amir Temur", "Khudoyar Khan"],
    ["Qual era la funzione di Sitorai Mokhi Khosa?", "Residenza di campagna dell'emiro di Bukhara", "Osservatorio", "Madrasa", "Caravanserraglio"],
    ["Quali tradizioni architettoniche si incontrano nella parte nuova del palazzo?", "Europea e bukhariana", "Cinese e giapponese", "Romana e gotica", "Indiana e maya"],
    ["Quale ambiente del palazzo è celebre per ganch e specchi?", "La Sala Bianca", "La Sala delle Stelle", "La Sala dei Leoni", "La Sala delle Colonne"],
    ["Quale museo è ospitato oggi a Sitorai Mokhi Khosa?", "Museo delle Arti Applicate", "Museo di Astronomia", "Museo della Metropolitana", "Museo della Carta"],
    ["A quale dinastia apparteneva Said Alim Khan?", "Mangyt", "Samanide", "Karakhanide", "Timuride"],
    ["A circa quale distanza da Bukhara sorge il palazzo?", "4 chilometri", "25 chilometri", "60 chilometri", "100 chilometri"],
    ["Che cosa significa il nome Registan?", "Luogo sabbioso", "Città verde", "Casa della sapienza", "Palazzo azzurro"],
    ["Qual era una funzione storica del Registan medievale?", "Centro amministrativo, commerciale e artigiano", "Porto fluviale", "Accampamento militare permanente", "Necropoli reale"],
    ["Sotto quale sovrano il Registan assunse un carattere più ufficiale?", "Ulugh Beg", "Gengis Khan", "Khudoyar Khan", "Ismail Samani"],
    ["Quale madrasa è la più antica delle tre del Registan?", "Madrasa di Ulugh Beg", "Sher-Dor", "Tilla-Kari", "Miri Arab"],
    ["In quali anni fu costruita la madrasa di Ulugh Beg al Registan?", "1417-1420", "1127-1130", "1619-1636", "1911-1920"],
    ["Oltre a governare, quale materia insegnò Ulugh Beg nella sua madrasa?", "Astronomia", "Ceramica", "Medicina chirurgica", "Calligrafia cinese"],
    ["Che cosa rappresentano le figure sul portale della madrasa Sher-Dor?", "Felini che inseguono gazzelle sotto un sole nascente", "Draghi intorno a una luna", "Cammelli davanti a una fortezza", "Pavoni accanto a una fontana"]
  ],
  6: [
    ["Che cosa significa Gur-e-Amir?", "Tomba dell'Emiro", "Porta della città", "Piazza sabbiosa", "Moschea blu"],
    ["Per chi fu inizialmente legato il mausoleo Gur-e-Amir?", "Muhammad Sultan, nipote di Amir Temur", "Ismail Samani", "Khudoyar Khan", "Kaffal ash-Shashi"],
    ["Dove morì Amir Temur nel 1405?", "Otrar", "Khiva", "Bukhara", "Kokand"],
    ["Verso quale paese era diretto Amir Temur nella sua ultima campagna?", "Cina", "India", "Persia", "Russia"],
    ["Di quale materiale è la celebre pietra tombale di Amir Temur?", "Giada", "Alabastro", "Granito rosso", "Bronzo"],
    ["Quante madrase compongono il Registan?", "Tre", "Due", "Quattro", "Cinque"],
    ["Quale madrasa del Registan significa 'dimora dei leoni'?", "Sher-Dor", "Tilla-Kari", "Ulugh Beg", "Miri Arab"],
    ["Chi commissionò la madrasa Sher-Dor?", "Yalangtush Bahadur", "Amir Temur", "Said Alim Khan", "Muhammad Amin Khan"],
    ["Quale edificio del Registan fungeva anche da moschea del venerdì?", "Tilla-Kari", "Sher-Dor", "Madrasa di Ulugh Beg", "Chor Minor"],
    ["In quali anni fu costruita la moschea Bibi Khanum?", "1399-1404", "1417-1420", "1819-1822", "1973-1977"],
    ["Dopo quale campagna Amir Temur avviò la costruzione di Bibi Khanum?", "La campagna in India", "La conquista della Cina", "La campagna in Russia", "La presa di Khiva"],
    ["A chi deve il nome la moschea Bibi Khanum?", "Saray Mulk Khanym", "La madre di Ulugh Beg", "Una poetessa di Bukhara", "La figlia di Gengis Khan"],
    ["Quante persone poteva accogliere circa la moschea Bibi Khanum?", "10.000", "1.000", "3.000", "50.000"],
    ["Come chiamavano i Greci l'antica Samarcanda?", "Maracanda", "Afrika", "Sogdiana", "Bactra"],
    ["Quale prodotto è particolarmente celebre al bazar Siab?", "Il pane di Samarcanda", "Il tè nero cinese", "Il caviale", "Il formaggio di yak"]
  ],
  7: [
    ["Che cosa significa il nome Shahrisabz?", "Città verde", "Città di pietra", "Porta del deserto", "Città della luna"],
    ["Quale grande condottiero nacque a Shahrisabz?", "Amir Temur", "Gengis Khan", "Alessandro Magno", "Khudoyar Khan"],
    ["Quale palazzo di Shahrisabz era la più grandiosa residenza di Amir Temur?", "Ak-Saray", "Tosh Hovli", "Sitorai Mokhi Khosa", "Kunya Ark"],
    ["Che cosa significa Ak-Saray?", "Palazzo Bianco", "Palazzo della Luna", "Palazzo delle Stelle", "Palazzo d'Estate"],
    ["Quale parte monumentale di Ak-Saray è ancora ben riconoscibile?", "I piloni dell'immenso portale", "Il tetto ligneo", "La sala del trono completa", "Il fossato colmo d'acqua"],
    ["A quale periodo appartengono soprattutto i grandi monumenti di Shahrisabz?", "Periodo timuride", "Periodo romano", "Periodo achemenide", "Periodo sovietico"],
    ["A quale uso era destinato il complesso Dorus-Saodat?", "Sepoltura della famiglia regnante", "Mercato coperto", "Osservatorio", "Scuola di ceramica"],
    ["Per quale figlio di Amir Temur fu avviato Dorus-Saodat?", "Jahangir", "Ulugh Beg", "Babur", "Shahrukh"],
    ["Quanti anni aveva Jahangir quando morì?", "22", "12", "35", "49"],
    ["In quale anno fu completato Dorus-Saodat secondo il portale turistico ufficiale?", "1392", "1127", "1688", "1871"],
    ["Oltre alle tombe, che cosa comprendeva Dorus-Saodat?", "Sala di preghiera, moschea e alloggi per religiosi e pellegrini", "Zecca e arsenale", "Terme e caravanserraglio", "Osservatorio e biblioteca scientifica"],
    ["Che cosa significa Kok-Gumbaz?", "Cupola blu", "Quattro torri", "Palazzo bianco", "Re vivente"],
    ["Chi fece costruire la moschea Kok-Gumbaz?", "Ulugh Beg", "Amir Temur", "Ismail Samani", "Khudoyar Khan"],
    ["In quali anni fu costruita Kok-Gumbaz?", "1434-1435", "1379-1380", "1619-1636", "1819-1822"],
    ["Di quale complesso è la moschea principale Kok-Gumbaz?", "Dorut-Tilovat", "Dorus-Saodat", "Poi Kalon", "Khast Imam"]
  ],
  8: [
    ["Che cosa significa Shah-i-Zinda?", "Re vivente", "Città verde", "Tomba dell'emiro", "Palazzo bianco"],
    ["A quale personaggio è legato il cuore religioso di Shah-i-Zinda?", "Qusam ibn Abbas", "Ismail Samani", "Kaffal ash-Shashi", "Khudoyar Khan"],
    ["Quale parentela aveva Qusam ibn Abbas con il profeta Maometto?", "Era suo cugino", "Era suo nonno", "Era suo figlio", "Era suo fratello"],
    ["Quali colori dominano nelle decorazioni di Shah-i-Zinda?", "Blu e turchese", "Rosso e nero", "Bianco e oro soltanto", "Verde e arancione"],
    ["Che tipo di complesso è Shah-i-Zinda?", "Una necropoli monumentale", "Un palazzo reale", "Un mercato coperto", "Una fortezza militare"],
    ["A quale arco cronologico appartengono gli edifici di Shah-i-Zinda?", "Dall'XI all'inizio del XX secolo", "Solo al XIV secolo", "Dal III al V secolo", "Dal XVIII al XIX secolo soltanto"],
    ["In quali anni fu costruito l'osservatorio di Ulugh Beg?", "1428-1429", "1399-1404", "1619-1636", "1819-1822"],
    ["Qual era la forma originaria dell'osservatorio?", "Circolare e a tre piani", "Quadrata e sotterranea", "Ottagonale e a un piano", "A croce con quattro minareti"],
    ["Quale grande strumento era il cuore dell'osservatorio?", "Un quadrante in marmo", "Un telescopio a specchio", "Una meridiana portatile", "Un astrolabio di legno"],
    ["Quante stelle circa furono catalogate da Ulugh Beg?", "1.018", "365", "212", "5.000"],
    ["Ulugh Beg compì le sue osservazioni con quale tecnologia?", "A occhio nudo e con strumenti monumentali", "Con telescopi elettronici", "Con satelliti", "Con una camera fotografica"],
    ["Quale valore calcolò con eccezionale precisione Ulugh Beg?", "La durata dell'anno siderale", "La distanza Terra-Luna col laser", "La velocità della luce", "L'età dell'universo"],
    ["Da quale pianta si ricava tradizionalmente la carta di Samarcanda a Konigil?", "Gelso", "Cotone", "Papiro", "Bambù"],
    ["Che cosa aziona i meccanismi della cartiera Meros?", "Una ruota ad acqua", "Un motore a vapore", "Il vento", "La forza animale"],
    ["Quale caratteristica ha la carta tradizionale di Konigil?", "Non viene sbiancata chimicamente", "È rivestita di plastica", "È fatta con legno di pino", "È prodotta solo a macchina"]
  ],
  9: [
    ["Qual era il soprannome del palazzo di Khudoyar Khan?", "Kokand Urda", "Palazzo Bianco", "Casa delle Quattro Torri", "Re Vivente"],
    ["In quale anno fu costruito il palazzo di Khudoyar Khan?", "1871", "1688", "1435", "1911"],
    ["Quanti anni aveva Khudoyar Khan quando salì al trono?", "12", "22", "35", "48"],
    ["Quante stanze aveva originariamente il palazzo?", "119", "19", "51", "212"],
    ["Quante stanze del palazzo sono conservate oggi?", "19", "9", "51", "98"],
    ["Quali artigiani contribuirono in modo decisivo alle decorazioni del palazzo?", "I ceramisti di Rishtan", "I cartai di Konigil", "I tessitori di Margilan", "Gli orafi di Khiva"],
    ["Dove è conservato oggi il trono di Khudoyar Khan?", "All'Ermitage di San Pietroburgo", "Al Louvre", "Al British Museum", "Nel Registan"],
    ["A quali anni risale la moschea Jami di Kokand?", "1819-1822", "1399-1404", "1417-1420", "1973-1977"],
    ["A quale sovrano è legata la costruzione della moschea Jami?", "Umar Khan", "Said Alim Khan", "Arslankhan", "Amir Temur"],
    ["Quante colonne lignee circondano il portico della moschea Jami?", "98", "40", "119", "212"],
    ["Quanto è alto il minareto della moschea Jami?", "22,5 metri", "10 metri", "46,4 metri", "80 metri"],
    ["Per quale materia prima è famosa la ceramica di Rishtan?", "Argilla rossa locale", "Marmo bianco", "Caolino nero", "Sabbia quarzifera"],
    ["Da quanto tempo, secondo la tradizione, si produce ceramica a Rishtan?", "Da oltre mille anni", "Da circa cento anni", "Dal periodo sovietico", "Dal XVII secolo soltanto"],
    ["Quale gamma cromatica caratterizza soprattutto la ceramica di Rishtan?", "Tonalità dell'azzurro", "Solo bianco e nero", "Rosso porpora uniforme", "Giallo e marrone senza smalto"],
    ["Su quale modello tradizionale lavora il Centro degli Artigiani di Rishtan?", "Maestro-apprendista", "Catena di montaggio", "Scuola militare", "Cooperativa agricola"]
  ],
  10: [
    ["Per quale prodotto artigianale è celebre Margilan?", "Seta", "Vetro soffiato", "Tappeti di lana tibetana", "Carta di papiro"],
    ["Come si chiama la storica fabbrica di seta visitabile a Margilan?", "Yodgorlik", "Meros", "Kokand Urda", "Sitorai"],
    ["In quale anno fu fondata la fabbrica Yodgorlik?", "1972", "1871", "1911", "2007"],
    ["Che cosa rende speciale la produzione di Yodgorlik?", "L'intero ciclo tradizionale è svolto manualmente", "Usa soltanto fibre sintetiche", "Produce esclusivamente tappeti", "Lavora solo seta importata già tessuta"],
    ["Quale sequenza si osserva durante la visita alla fabbrica?", "Dal bozzolo al tessuto finito", "Dall'argilla alla ceramica", "Dal gelso alla carta", "Dal minerale alla moneta"],
    ["Che cos'è il khan-atlas?", "Un tessuto di seta tradizionale", "Una carta geografica reale", "Una ceramica azzurra", "Un copricapo di feltro"],
    ["Che cos'è l'adras?", "Un tessuto semiseta", "Un tipo di minareto", "Una varietà di riso", "Un pigmento per ceramica"],
    ["Quali materiali naturali possono essere usati per tingere il khan-atlas?", "Bucce di melograno, radici e bucce di cipolla", "Solo carbone e gesso", "Petrolio e catrame", "Sale e sabbia"],
    ["Quale tecnica decorativa crea i motivi sfumati tipici di atlas e adras?", "Ikat, tingendo i fili prima della tessitura", "Affresco su tessuto finito", "Stampa fotografica", "Ricamo a punto croce soltanto"],
    ["In quale anno la pratica di atlas e adras di Margilan entrò nel registro UNESCO delle buone pratiche?", "2017", "1991", "2000", "2024"],
    ["Quale evento celebra ogni anno la tradizione tessile di Margilan?", "Atlas Bayrami", "Navruz Registan", "Festival del Kyzylkum", "Giornata di Kalta Minor"],
    ["Quale foglia alimenta il baco da seta?", "Gelso", "Vite", "Cotone", "Tè"],
    ["Quale rischio può causare la chiusura del passo Kamchik in inverno?", "Valanghe e colate di fango", "Maree", "Eruzioni vulcaniche", "Tempeste tropicali"],
    ["Quale funzione geografica svolge il passo Kamchik?", "Collega la valle di Fergana con Tashkent", "Collega Khiva al Mar d'Aral", "Unisce Bukhara e il Kyzylkum", "Attraversa il confine con l'Afghanistan"],
    ["Quale caratteristica descrive la valle di Fergana?", "È circondata da alte catene montuose", "È una pianura costiera", "È interamente desertica", "È un'isola fluviale"]
  ],
  11: [
    ["Quale museo di Tashkent fu inaugurato nel 1996?", "Museo Statale dei Timuridi", "Museo della Carta di Meros", "Museo dell'Ark", "Museo di Ichan Kala"],
    ["Per quale anniversario fu aperto il Museo dei Timuridi?", "660º anniversario della nascita di Amir Temur", "100º anniversario dell'indipendenza", "500º anniversario di Ulugh Beg", "Millenario della Via della Seta"],
    ["Quale forma caratterizza l'edificio del Museo dei Timuridi?", "Pianta rotonda con cupola", "Piramide di vetro", "Torre quadrata", "Basilica rettangolare"],
    ["Quanti reperti conserva approssimativamente il Museo dei Timuridi?", "Più di 3.000", "Circa 300", "Esattamente 660", "Più di 50.000"],
    ["A chi è dedicata la grande statua equestre in Piazza Amir Temur?", "Amir Temur", "Ulugh Beg", "Alisher Navoi", "Ismail Samani"],
    ["In quale anno fu sistemata Piazza Amir Temur nella sua veste dell'Uzbekistan indipendente?", "1993", "1966", "1977", "2000"],
    ["Quale evento naturale distrusse gran parte di Tashkent nel 1966?", "Un terremoto", "Un'alluvione", "Una valanga", "Un'eruzione"],
    ["Quale parte storica sopravvisse in misura significativa al terremoto del 1966?", "L'area di Khast Imam nella città vecchia", "Il quartiere dell'aeroporto", "La linea Yunusabad", "La torre televisiva"],
    ["Con quale nome era nota la cittadella medievale di Tashkent?", "Shakhristan", "Ichan Kala", "Afrasiab", "Dorus-Saodat"],
    ["Vicino a quale area attuale sorgeva la città medievale di Tashkent?", "Chorsu", "Piazza Registan", "Kunya Ark", "Passo Kamchik"],
    ["In quale anno Tashkent fu conquistata dai Mongoli?", "1220", "1127", "1598", "1871"],
    ["Quale stazione della metro è collegata ad Alisher Navoi da un passaggio di interscambio?", "Paxtakor", "Chorsu", "Kosmonavtlar", "Mustaqillik Maydoni"],
    ["Quale particolarità culturale si trova nell'interscambio Alisher Navoi-Paxtakor?", "Una sala di lettura con biblioteca", "Un laboratorio di seta", "Una zecca", "Un planetario sotterraneo"],
    ["Quale edificio culturale di Tashkent fu completato nel 1947?", "Teatro dell'Opera Alisher Navoi", "Museo dei Timuridi", "Torre televisiva", "Madrasa Barak Khan"],
    ["Quale monumento moderno fu inaugurato nel 2000?", "Memoriale delle vittime della repressione", "Kalta Minor", "Mausoleo dei Samanidi", "Moschea Bibi Khanum"]
  ]
};
